### ISSUE TITLE
难以描述的问题

### ISSUE THREAD

**Issue by quentin-qiao** [tonylu110/uyou-todo-electron#13]
对一部分TODO进行修改以后，有一定概率会使其他未修改的TODO也变成已修改TODO的内容

**Comment by tonylu110** [comment]
可能是服务器的问题，纯离线的情况下用应该是完全没问题的

**Comment by quentin-qiao** [comment]
但是，关闭自动同步后，这个问题不再复现，或许这是同步出错

**Comment by tonylu110** [comment]
因为我没复现出现过，所以暂时也不清楚问题所在
