### ISSUE TITLE
电脑的主题为深色模式下显示不正常

### ISSUE THREAD

**Issue by BlackMulberry** [tonylu110/uyou-todo-electron#24]
![QQ截图20231104233211](https://github.com/tonylu110/uyou-todo-electron/assets/94740668/48812a78-9905-45a1-94a6-9ed89780c28c)
电脑主题是深色模式，uyou里选随系统变换和浅色模式都是这样，左边全黑，uyou的深色模式是正常的
不过只有第一次打开的时候是这样，在毛玻璃的选项随便点一下，再选回浅色模式就正常了
系统是win11 23H2

**Comment by tonylu110** [comment]
这个是一个 Windows 的 bug，也可能是我的 bug，重启几次软件应该就好了
