### ISSUE TITLE
新功能提议

### ISSUE THREAD

**Issue by ConfusedOneself** [tonylu110/uyou-todo-electron#3]
1.建议可以加入开机自启的开关
2.简易模式可以记录上次窗口的摆放位置，而不是打开软件就出现在桌面正中央

**Comment by tonylu110** [comment]
窗口位置记录已经在做了，开机自启应该也会在下个版本更新

**Comment by tonylu110** [comment]
已经更新了，欢迎下载体验 [1.2.3 version](https://github.com/tonylu110/uyou-todo-electron/releases/tag/1.2.3)
