### ISSUE TITLE
Can I add a search function

### ISSUE THREAD

**Issue by MAKER555** [tonylu110/uyou-todo-electron#32]
Add features to search for content，【添加功能：搜索内容】

**Comment by tonylu110** [comment]
> Add features to search for content，【添加功能：搜索内容】

会有，但是要一点时间

**Comment by MAKER555** [comment]
> > Add features to search for content，【添加功能：搜索内容】
> 
> 会有，但是要一点时间

好的。希望添加全局快捷键，方便唤醒主界面。

**Comment by tonylu110** [comment]
> > > Add features to search for content，【添加功能：搜索内容】
> > 
> > 会有，但是要一点时间
> 
> 好的。希望添加全局快捷键，方便唤醒主界面。

快捷键可能这几个版本就会有，搜索功能未来的大版本更新会带上
