### ISSUE TITLE
设置提醒时间发生错误

### ISSUE THREAD

**Issue by YU-7** [tonylu110/uyou-todo-electron#36]
todo 设置提醒时间，提醒时间到了就出现这个错误了
操作系统：win11家庭版
![image](https://github.com/tonylu110/uyou-todo-electron/assets/58320198/9cb6f658-3f65-4306-85c9-ff055043b238)

**Comment by tonylu110** [comment]
是在设置时出错还是到时间推送时出错

**Comment by tonylu110** [comment]
已经排查出错误，明天更新版本后解决
