### ISSUE TITLE
毛玻璃特效问题

### ISSUE THREAD

**Issue by Sekai363** [tonylu110/uyou-todo-electron#44]
安装后打开毛玻璃特效显示完美，软件重启后显示不正常

**Comment by tonylu110** [comment]
> 安装后打开毛玻璃特效显示完美，软件重启后显示不正常

什么系统，再次重启后是否会复现

**Comment by Sekai363** [comment]
win10 1809，再次重启依然会

**Comment by Sekai363** [comment]
<img width="637" alt="捕获" src="https://github.com/user-attachments/assets/3f29cdd3-2559-4f34-ae07-e57f6fa64774">
如图暗色模式显示这样，只能关了才能用

**Comment by tonylu110** [comment]
> <img width="637" alt="捕获" src="https://github.com/user-attachments/assets/3f29cdd3-2559-4f34-ae07-e57f6fa64774">
> 如图暗色模式显示这样，只能关了才能用

win10 下的暗色模式可能是有问题，后续看怎么解决

**Comment by Sekai363** [comment]
感激不尽，还有能不能拜托大佬加一个类似番茄钟的可视化计时功能，沙漏或者时间进度条都行，现在的提醒功能不太明显，想用pc的时候能看个大概时间进度，真的麻烦您了

**Comment by tonylu110** [comment]
> 感激不尽，还有能不能拜托大佬加一个类似番茄钟的可视化计时功能，沙漏或者时间进度条都行，现在的提醒功能不太明显，想用pc的时候能看个大概时间进度，真的麻烦您了

maybe 后面几个版本会加吧

**Comment by Sekai363** [comment]
大佬，打扰了，发现lite版本的毛玻璃特效没有问题，重启也正常
