### ISSUE TITLE
窗口缩放问题

### ISSUE THREAD

**Issue by 18lenda** [tonylu110/uyou-todo-electron#47]
如图所示，在标准状态下打开侧边栏再打开设置主页会往右侧缩放，但是在关闭侧边栏后主页不会自动返回，留了一部分空白，点击设置的向左返回箭头后还是这样，把窗口放到最大问题依然存在，只能关闭程序重新打开。
![1](https://github.com/user-attachments/assets/0a8cb7ff-3507-4590-bc05-e88c16f2894b)
![2](https://github.com/user-attachments/assets/262f28e8-f6a0-4ff9-a976-c80830efbe3d)

**Comment by tonylu110** [comment]
> 如图所示，在标准状态下打开侧边栏再打开设置主页会往右侧缩放，但是在关闭侧边栏后主页不会自动返回，留了一部分空白，点击设置的向左返回箭头后还是这样，把窗口放到最大问题依然存在，只能关闭程序重新打开。
> ![1](https://github.com/user-attachments/assets/0a8cb7ff-3507-4590-bc05-e88c16f2894b)
> ![2](https://github.com/user-attachments/assets/262f28e8-f6a0-4ff9-a976-c80830efbe3d)
> 

关闭浮动模式呢

**Comment by tonylu110** [comment]
问题已找到原因，下个版本修复
