### ISSUE TITLE
点击侧边栏第一个按钮之后页面组件不会动态调整

### ISSUE THREAD

**Issue by NikoAoi** [tonylu110/uyou-todo-electron#48]
**问题描述**：
点击侧边栏的收缩展开按钮之后页面组件不会动态调整，且部分组件不显示
![image](https://github.com/user-attachments/assets/5bc005ed-736c-4654-8f9e-3c3647026e6d)

**复现步骤**：
依次点击“我的一天”、“加星TODO”以及“未完成”这三个组件后，再点击侧边栏的收缩展开按钮即可稳定复现
![image](https://github.com/user-attachments/assets/b755ebf3-e0f5-4653-9434-b9d68a2e2004)

**Comment by tonylu110** [comment]
已知，下个版本修复，最近有点忙，这个月底前应该会更新修复

**Comment by tonylu110** [comment]
这个问题已解决 [3.1.0](https://github.com/tonylu110/uyou-todo-electron/releases/tag/3.1.0)
